Getting started guide draft
DolbyIO/comms-sdk-dotnet pull request #126
Opened 2023-01-08 23:33 UTC by jfan-dolby

Initial PR, more changes to come. Please only review, do not approve just yet. 
For copyeditor, please directly push to the branch (doc-update)

2023-01-09 16:49 UTC, 4thlabs approved these changes

2023-01-10 00:01 UTC, FabienLavocat submitted a review, later dismissed

2023-01-10 21:09 UTC, FabienLavocat submitted a review, later dismissed

2023-01-10 22:29 UTC, FabienLavocat requested changes

2023-01-10 22:29 UTC, FabienLavocat commented on docs/documentation/unity/getting-started/initialization.md
> +To start fresh, you can create a new project from the Unity Hub. This guide use the `Third Person` template in Unity version 2021.3.6f1 LTS. The following video shows the workflow:
`use` => `uses`

2023-01-11 00:08 UTC, FabienLavocat requested changes

2023-01-11 00:08 UTC, FabienLavocat commented on docs/documentation/unity/getting-started/initialization.md
> +2. Add a new script to the `Script Machine` component. In the component click the `New` button and name and save your new script. Start editing the script with the `Edit Graph` button.
`In the component click, the`

2023-01-11 00:08 UTC, FabienLavocat commented on docs/documentation/unity/getting-started/initialization.md
> +To start fresh, you can create a new project from the Unity Hub. This guide use the `Third Person` template in Unity version 2021.3.6f1 LTS.
`This guide uses the`

2023-01-11 00:08 UTC, FabienLavocat commented on docs/documentation/unity/getting-started/initialization.md
> +You should have signed up in Dolby.io by now. In the app that is automatically created for you in the Dolby.io dashboard, acquire a temporary Client Access Token and paste in the `String` literal nod
`and paste it in the`

2023-01-11 00:08 UTC, FabienLavocat commented on docs/documentation/unity/getting-started/initialization.md
> +You should have signed up in Dolby.io by now. In the app that is automatically created for you in the Dolby.io dashboard, acquire a temporary Client Access Token and paste in the `String` literal nod
`the token you acquired expires after 12 hours`

2023-01-11 01:10 UTC, FabienLavocat approved these changes

2023-01-11 11:37 UTC, 4thlabs approved these changes

2023-01-11 11:37 UTC, merged